name: "Terraform Pull Request Builder"

on:
  pull_request:
    branches:
      - master

jobs:
  plan:
    name: "Terraform Plans"
    runs-on: x2-runners #ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.18

      - name: "Path Filter"
        uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            sandbox:
              - 'sandbox/**/*'
            nonprod:
              - 'nonprod/**/*'
            prod:
              - 'prod/**/*'

      - name: "Sandbox Root Module Init"
        if: steps.filter.outputs.sandbox == 'true'
        id: sandbox-init
        run: cd sandbox && terraform init -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SRE_TERRAFORM_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SRE_TERRAFORM_AWS_SECRET_KEY }}

      - name: "Nonprod Root Module Init"
        if: steps.filter.outputs.nonprod == 'true'
        id: nonprod-init
        run: cd nonprod && terraform init -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SRE_TERRAFORM_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SRE_TERRAFORM_AWS_SECRET_KEY }}

      - name: "Prod Root Module Init"
        if: steps.filter.outputs.prod == 'true'
        id: prod-init
        run: cd prod && terraform init -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SRE_TERRAFORM_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SRE_TERRAFORM_AWS_SECRET_KEY }}

      - name: "Sandbox Root Module Validation"
        if: steps.filter.outputs.sandbox == 'true'
        id: sandbox-validation
        run: cd sandbox && terraform validate -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SRE_TERRAFORM_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SRE_TERRAFORM_AWS_SECRET_KEY }}

      - name: "NonProd Root Module Validation"
        if: steps.filter.outputs.nonprod == 'true'
        id: nonprod-validation
        run: cd nonprod && terraform validate -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SRE_TERRAFORM_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SRE_TERRAFORM_AWS_SECRET_KEY }}

      - name: "Prod Root Module Validation"
        if: steps.filter.outputs.prod == 'true'
        id: prod-validation
        run: cd prod && terraform validate -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SRE_TERRAFORM_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SRE_TERRAFORM_AWS_SECRET_KEY }}

      - name: "Sandbox Root Module Plan"
        if: steps.filter.outputs.sandbox == 'true'
        id: sandbox-plan
        run: cd sandbox && terraform plan -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SRE_TERRAFORM_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SRE_TERRAFORM_AWS_SECRET_KEY }}

      - name: "NonProd Root Module Plan"
        if: steps.filter.outputs.nonprod == 'true'
        id: nonprod-plan
        run: cd nonprod && terraform plan -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SRE_TERRAFORM_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SRE_TERRAFORM_AWS_SECRET_KEY }}

      - name: "Prod Root Module Plan"
        if: steps.filter.outputs.prod == 'true'
        id: prod-plan
        run: cd prod && terraform plan -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SRE_TERRAFORM_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SRE_TERRAFORM_AWS_SECRET_KEY }}

      - name: "Sandbox Plan Comment"
        if: steps.filter.outputs.sandbox == 'true'
        id: sandbox-plan-comment
        uses: actions/github-script@0.9.0
        env:
          TF_PLAN: "terraform\n${{ steps.sandbox-plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Sandbox Environment Terraform Plan \`
            #### Sandbox Environment Terraform Validation 🤖${{ steps.sandbox-validation.outputs.stdout }}
            #### Sandbox Environment Terraform Plan 📖\`${{ steps.sandbox-plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`${process.env.TF_PLAN}\`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: "NonProd Plan Comment"
        if: steps.filter.outputs.nonprod == 'true'
        id: nonprod-plan-comment
        uses: actions/github-script@0.9.0
        env:
          TF_PLAN: "terraform\n${{ steps.nonprod-plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### NonProd Environment Terraform Plan \`
            #### NonProd Environment Terraform Validation 🤖${{ steps.nonprod-validation.outputs.stdout }}
            #### NonProd Environment Terraform Plan 📖\`${{ steps.nonprod-plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`${process.env.TF_PLAN}\`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: "Prod Plan Comment"
        if: steps.filter.outputs.prod == 'true'
        id: prod-plan-comment
        uses: actions/github-script@0.9.0
        env:
          TF_PLAN: "terraform\n${{ steps.prod-plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Prod Environment Terraform Plan \`
            #### Prod Environment Terraform Validation 🤖${{ steps.prod-validation.outputs.stdout }}
            #### Prod Environment Terraform Plan 📖\`${{ steps.prod-plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`${process.env.TF_PLAN}\`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
